vscode:
  extensions:
    - eamodio.gitlens
    - yzhang.markdown-all-in-one
    - TakumiI.markdowntable
    - ms-azuretools.vscode-docker
    - jeff-hykin.better-dockerfile-syntax
    - timonwong.shellcheck
