#!/usr/bin/env bash

BACKUP_DIR=${BACKUP_DIR:-/backups}
BACKUP_FILE_PREFIX=${BACKUP_FILE_PREFIX:-backup}
BACKUP_KEEP_DAYS=${BACKUP_KEEP_DAYS:-NONE}
BACKUP_ZIP_FILES=${BACKUP_ZIP_FILES:-true}

POSTGRES_HOST=${POSTGRES_HOST:-localhost}
POSTGRES_PORT=${POSTGRES_PORT:-5432}
POSTGRES_DB=${POSTGRES_DB:-}
POSTGRES_DATABASES=${POSTGRES_DATABASES:-}
POSTGRES_USER=${POSTGRES_USER:-}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-}

BACKUP_SOURCE=${BACKUP_SOURCE:-/data}
BACKUP_TARGET=${BACKUP_TARGET:-${BACKUP_SOURCE}}

GCS_BUCKET=${GCS_BUCKET:-}
GCS_KEY_FILE_PATH=${GCS_KEY_FILE_PATH:-/keys/gcs-key.json}
