#!/usr/bin/env bash

### View backups
###
### Usage:
###     $ docker-compose -f <environment>.yml (exec |run --rm) backup_helper backup_ls

set -o errexit
set -o pipefail
set -o nounset

working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

message_welcome "The following backups are on the directory '${BACKUP_DIR}':"

ls -lht "${BACKUP_DIR}"
