#!/usr/bin/env bash

### List backups on a Google Cloud Storage Bucket
###
### Usage:
###     $ docker-compose -f <environment>.yml (exec |run --rm) backup_helper gcs_ls

set -o errexit
set -o pipefail
set -o nounset

working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"
source "${working_dir}/_sourced/make_boto_config.sh"

message_welcome "The following backups are on the Google Bucket '${GCS_BUCKET}':"

if [[ ! "${GCS_BUCKET}" =~ gs://* ]]; then
    GCS_BUCKET="gs://${GCS_BUCKET}"
fi

gsutil ls -lrh ${GCS_BUCKET}
