#!/usr/bin/env bash

### Upload backups to a Google Cloud Storage Bucket
###
### Usage:
###     $ docker-compose -f <environment>.yml (exec |run --rm) backup_helper gcs_upload

set -o errexit
set -o pipefail
set -o nounset

working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"
source "${working_dir}/_sourced/make_boto_config.sh"

message_welcome "Upload the backups from directory '${BACKUP_DIR}' to GCS Bucket '${GCS_BUCKET}'..."

if [[ ! "${GCS_BUCKET}" =~ gs://* ]]; then
    GCS_BUCKET="gs://${GCS_BUCKET}"
fi

gsutil -m cp -n -r $BACKUP_DIR/. $GCS_BUCKET

message_success "The files from directory '${BACKUP_DIR}' have been uploaded to GCS Bucket '${GCS_BUCKET}'."
