#!/usr/bin/env bash

### Download backups from a Google Cloud Storage Bucket
###
### Parameters:
###     <1> filename of an existing backup on the GCS Bucket
###
### Usage:
###     $ docker-compose -f <environment>.yml (exec |run --rm) backup_helper gcs_download <1>

set -o errexit
set -o pipefail
set -o nounset

working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"
source "${working_dir}/_sourced/make_boto_config.sh"

backup_filename="${1}"

message_welcome "Download the file '${backup_filename}' from GCS Bucket '${GCS_BUCKET}'..."

if [[ ! "$GCS_BUCKET" =~ gs://* ]]; then
    GCS_BUCKET="gs://${GCS_BUCKET}"
fi

gsutil -m cp "${GCS_BUCKET}/${backup_filename}" "${BACKUP_DIR}/${backup_filename}"

message_success "The file '${backup_filename}' has been downloaded from GCS Bucket '${GCS_BUCKET}' to directory '${BACKUP_DIR}'."
